import Head from 'next/head';
import React from 'react';
import TodoForm from '../components/TodoForm';
import TodoList from '../components/TodoList';
import { getTodos } from "../lib/prisma";

export default async function Home(){

  const todo = await getTodos();
  const parsedTodos = todo ? todo : null;
  return (
    <div className='bg-black h-screen'>
      <main className='p-24'>
      <Head>
        <title>Todo App</title>
        <meta name='description' content='Generated by create next app' />  
      </Head>
	  <header className=''>
      <h2 className='text-2xl font-bold select-none text-white pb-5 pt-4 text-[40px]'>MyTodos</h2>
      </header>
      
        <TodoForm />
        <TodoList data={parsedTodos}/>
      </main>
    </div>
  );
};