import Head from 'next/head';
import React from 'react';
import TodoForm from '../components/TodoForm';
import TodoList from '../components/TodoList';
import { getTodos } from "../lib/prisma";

export default async function Home(){

  const todo = await getTodos();
  const parsedTodos = todo ? todo : null;
  return (
    <div className='max-w-screen-lg mx-auto bg-black'>
      <main className='w-2/3 mx-auto border-b'>
      <Head>
        <title>Todo App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
	  <header className='p-6 md:border border-b'>
      <h2 className='text-2xl font-semibold select-none'>MyTodos</h2>
      </header>
      
        <TodoForm />
        <TodoList data={parsedTodos}/>
      </main>
    </div>
  );
};