import Head from 'next/head';
import React from 'react';
import TodoForm from '../components/TodoForm';
import TodoList from '../components/TodoList';
import { getTodos } from "../lib/prisma";

export default async function Home(){

  const todo = await getTodos();
  const parsedTodos = todo ? todo : null;
  return (
    <div className='bg-black h-screen'>
      <main className='p-24'>
      <Head>
        <title>Todo App</title>
        <meta name='description' content='Generated by create next app' />  
      </Head>
	  <header className='flex items-center gap-6'>
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" className="w-9 h-9 text-white">
        <path stroke-linecap="round" stroke-linejoin="round" d="m16.862 4.487 1.687-1.688a1.875 1.875 0 1 1 2.652 2.652L10.582 16.07a4.5 4.5 0 0 1-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 0 1 1.13-1.897l8.932-8.931Zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0 1 15.75 21H5.25A2.25 2.25 0 0 1 3 18.75V8.25A2.25 2.25 0 0 1 5.25 6H10" />
      </svg>

        <h2 className='text-2xl font-bold select-none text-white pb-8 pt-4 text-[40px] mt-2'>To-Do List</h2>
      </header>
      
        <TodoForm />
        <TodoList data={parsedTodos}/>
      </main>
    </div>
  );
};